## Related Works

```{r echo=FALSE, message=FALSE, warning=FALSE}
source("R/common.R")
source("R/latex.R")
source("R/kable.R")
LoadPackage("tidyverse")
LoadPackage("kableExtra")
LoadPackage("ggpubr")
LoadPackage("ggplot2")
```

### v1

```{r}
relatedWorks <- read.csv2("csv/related-works.csv")
```

```{r echo=FALSE}
CreateScrollableTable(t(relatedWorks))
```

```{r echo=FALSE}
SaveLatexTable(t(relatedWorks), "Comparision of existing solutions and PULCEO.", "comparison-of-existing-solutions-and-pulceo", "comparison-of-existing-solutions-and-pulceo.tex", "tb", "table")
```

### Functional Requirements

```{r}
file_name <- "csv/related-works-fr.csv"

# Read the file with skip and manually define column names
relatedWorksFR <- read.csv2(file_name, skip = 1, header = FALSE, quote = "")

# Read just the first line separately to extract column names
header_line <- readLines(file_name, n = 1)
col_names <- strsplit(header_line, ";")[[1]]
colnames(relatedWorksFR) <- col_names
```

```{r echo=FALSE}
CreateScrollableTable(relatedWorksFR)
```

```{r echo=FALSE}
excluded_columns <- c("Entity")

relatedWorksFR <- relatedWorksFR %>%
    mutate(Phase = factor(Phase,
        levels = c(
            "All", "Creation", "Monitoring",
            "Operation", "Evaluation", "Documentation"
        ),
        ordered = TRUE
    )) %>%
    arrange(Phase, No.) %>%
    select(-all_of(excluded_columns)) 

align = c("l","l","l","l","l","l","l","l","l","l","l")

SaveMultiRowLatexTable(relatedWorksFR, "Comparison of Functional Requirements of Related Works and PULCEO", "comparison-related-works-pulceo-fr", "comparison-related-works-pulceo-fr.tex", "tb", "table", 2, align)
```


### Non-Functional Requirements

```{r}
file_name <- "csv/related-works-nfr.csv"

# Read the file with skip and manually define column names
relatedWorksNFR <- read.csv2(file_name, skip = 1, header = FALSE, quote = "")

# Read just the first line separately to extract column names
header_line <- readLines(file_name, n = 1)
col_names <- strsplit(header_line, ";")[[1]]
colnames(relatedWorksNFR) <- col_names
```

```{r echo=FALSE}
CreateScrollableTable(relatedWorksNFR)
```

```{r echo=FALSE}
excluded_columns <- c("Entity")

relatedWorksNFR <- relatedWorksNFR %>%
    mutate(Phase = factor(Phase,
        levels = c(
            "All", "Creation", "Monitoring",
            "Operation", "Evaluation", "Documentation"
        ),
        ordered = TRUE
    )) %>%
    arrange(Phase, No.) %>%
    select(-all_of(excluded_columns)) 

align = c("l","l","l","l","l","l","l","l","l","l","l")

SaveMultiRowLatexTable(relatedWorksNFR, "Comparison of Non-functional Requirements of Related Works and PULCEO", "comparison-related-works-pulceo-nfr", "comparison-related-works-pulceo-nfr.tex", "tb", "table", 2, align)
```
