Vagrant.configure(2) do |config| 
  config.vm.define "pulceo-microos-node-632611c1-0306-4d9b-b8cf-94dd16eb0a87-0" do |a|
    a.vm.synced_folder ".", "/vagrant", disabled: 'true'
    a.vm.box = "opensuse/MicroOS-ContainerHost.x86_64"
    a.vm.box_version = "16.0.0.20240109"
    a.vm.hostname = "pulceo-microos-node-632611c1-0306-4d9b-b8cf-94dd16eb0a87-0"
    a.vm.provider "libvirt" do |libvirt|
      libvirt.memory = 1024
      libvirt.cpus = 1
      libvirt.storage :file, :device => :cdrom, :path => "/tmp/ios-microos/combustion-0.iso"
      libvirt.tpm_model = "tpm-crb"
      libvirt.tpm_type = "emulator"
      libvirt.tpm_version = "2.0"
    end
    a.vm.network "private_network", ip: "192.168.125.10", auto_config: false
  end

  config.vm.define "pulceo-microos-node-632611c1-0306-4d9b-b8cf-94dd16eb0a87-1" do |b|
    b.vm.synced_folder ".", "/vagrant", disabled: 'true'
    b.vm.box = "opensuse/MicroOS-ContainerHost.x86_64"
    b.vm.box_version = "16.0.0.20240109"
    b.vm.hostname = "pulceo-microos-node-632611c1-0306-4d9b-b8cf-94dd16eb0a87-1"
    b.vm.provider "libvirt" do |libvirt|
      libvirt.memory = 1024
      libvirt.cpus = 1
      libvirt.storage :file, :device => :cdrom, :path => "/tmp/ios-microos/combustion-1.iso"
      libvirt.tpm_model = "tpm-crb"
      libvirt.tpm_type = "emulator"
      libvirt.tpm_version = "2.0"
    end
    b.vm.network "private_network", ip: "192.168.125.11", auto_config: false
  end
end
