---
params:
  rootfolder: "."
  subfolder: "sample"
---

```{r setup-topology, include=FALSE}
knitr::opts_knit$set(root.dir = here())
```

```{r topology-directories, child = 'directories.Rmd' }
```

```{r topology-r, include=FALSE, echo=FALSE}
source(here("includes/R/tables.R"))
```

```{r topology-data, include=FALSE, echo=FALSE}
source(here("includes/resources/providers.R"))
source(here("includes/resources/nodes.R"))
source(here("includes/resources/links.R"))
source(here("includes/resources/metric-requests.R"))
source(here("includes/resources/applications.R"))
```

## Topology

```{r topology-providers, eval=nrow(providers) > 0, child = 'includes/topology/providers.Rmd', include=TRUE, echo=FALSE}
```

```{r topology-nodes, eval=(NODES_PRESENT) > 0, child = 'includes/topology/nodes.Rmd', include=TRUE, echo=FALSE}
```

```{r topology-links, eval=(LINKS_PRESENT) > 0, child = 'includes/topology/links.Rmd', include=TRUE, echo=FALSE}
```

```{r topology-metric-requests, eval=(METRIC_REQUESTS_PRESENT) > 0, child = 'includes/topology/metric-requests.Rmd', include=TRUE, echo=FALSE}
```

```{r topology-applications, eval=(APPLICATIONS_PRESENT) > 0, child = 'includes/topology/applications.Rmd', include=TRUE, echo=FALSE}
```
