providers <- jsonlite::fromJSON(here(paste(FOLDER_PFX_RAW, "PROVIDERS.json", sep = "/")))
nodes <- jsonlite::fromJSON(here(paste(FOLDER_PFX_RAW, "NODES.json", sep = "/")))
links <- jsonlite::fromJSON(here(paste(FOLDER_PFX_RAW, "LINKS.json", sep = "/")))
metric_requests <- jsonlite::fromJSON(here(paste(FOLDER_PFX_RAW, "METRIC_REQUESTS.json", sep = "/")))
applications <- jsonlite::fromJSON(here(paste(FOLDER_PFX_RAW, "METRIC_REQUESTS.json", sep = "/")))
