#!/bin/bash
# combustion: network prepare
set -euxo pipefail

### --- START VARIABLES --- ###
NODE_HOSTNAME="pulceo-microos-node-632611c1-0306-4d9b-b8cf-94dd16eb0a87-1"
### --- END VARIABLES --- ###

### --- START NETWORK CONFIGURATION --- ###

nm_config() {
    umask 077 # Required for NM config
    mkdir -p /etc/NetworkManager/system-connections/
    
    cat >/etc/NetworkManager/system-connections/dynamic.nmconnection <<-EOF
    [connection]
    id=dynamic
    type=ethernet
    interface-name=ens5
    autoconnect=true

    [ipv4]
    method=auto
EOF

    cat >/etc/NetworkManager/system-connections/static.nmconnection <<-EOF
    [connection]
    id=static
    type=ethernet
    interface-name=ens6
    autoconnect=true

    [ipv4]
    method=manual
    dns=192.168.125.1
    address1=192.168.125.10/24,192.168.125.1
EOF
}

if [ "${1-}" = "--prepare" ]; then
    nm_config # Configure NM in the initrd
    exit 0
fi

# Redirect output to the console
exec > >(exec tee -a /dev/tty0) 2>&1
nm_config # Configure NM in the system
curl example.com

### --- END NETWORK CONFIGURATION --- ###

### --- START SYSTEM CONFIGURATION --- ###

## Set hostname
echo $NODE_HOSTNAME > /etc/hostname

# Set a password for root, generate the hash with "openssl passwd -6"
echo 'root:$6$sJ7HRQHeyKIilmc6$uM729dc/w11EMwf2Ywf0Shp9O9cHpZ2h.MPUatITZrgQ53HTvk8iRW5i8LKvIZoNSvDGYgORUjUo6MXVd1dZ11' | chpasswd -e
# Add a public ssh key and enable sshd
mkdir -pm700 /root/.ssh/
echo 'ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBO6ThrVoB8yod4TFlffB2W117yjzILpwX/Jv/HkSwJE868aNvxPCtWwICHLTWV3wgqtkWcLXF1wLsoLq60hhNPg= sebastian.boehm@d162046.dhcp.netz-service.uni-bamberg.de' >> /root/.ssh/authorized_keys
systemctl enable sshd.service

### --- END SYSTEM CONFIGURATION --- ###

### --- START K3S INSTALLATION --- ###

### --- END K3S INSTALLATION --- ###


# Leave a marker
echo "Configured with combustion" > /etc/issue.d/combustion