---
title: "PULCEO Orchestration Reports" 
knit: (function(input_file, encoding) {
  metadata <- rmarkdown::yaml_front_matter(input_file);
  out_dir <- with(metadata, "reports");
  rmarkdown::render(input_file,
  encoding=encoding,
  output_file=file.path(dirname(input_file), out_dir, "index.html"))})
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r, include=FALSE}
# set this option in the first code chunk in the document
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, include = FALSE)
options(knitr.duplicate.label = 'allow')
```

## SummerSoC 2025

[Orchestration Report](summersoc2025)

```{r echo=FALSE }
subfolder3 <- "summersoc2025"
rmarkdown::render('pulceo-data-analytics-offloading.Rmd', 
                  params = list(subfolder = subfolder3),
                  output_dir = paste0("reports", "/", subfolder3),
                  output_file = "index.html")
```

## SOSE 2024 PROD

[Orchestration Report](sose2024-prod)

```{r echo=FALSE }
subfolder2 <- "sose2024-prod"
rmarkdown::render('pulceo-data-analytics.Rmd', 
                  params = list(subfolder = subfolder2),
                  output_dir = paste0("reports", "/", subfolder2),
                  output_file = "index.html")
```

## SummerSoC 2024 PROD-IDLE

[Orchestration Report](summersoc2024-prod-idle)

```{r echo=FALSE }
subfolder0 <- "summersoc2024-prod-idle"
rmarkdown::render('pulceo-data-analytics.Rmd', 
                  params = list(subfolder = subfolder0),
                  output_dir = paste0("reports", "/", subfolder0),
                  output_file = "index.html")
```

## SummerSoC 2024 PROD-LOAD

[Orchestration Report](summersoc2024-prod-load)

```{r echo=FALSE }
subfolder1 <- "summersoc2024-prod-load"
rmarkdown::render('pulceo-data-analytics.Rmd', 
                  params = list(subfolder = subfolder1),
                  output_dir = paste0("reports", "/", subfolder1),
                  output_file = "index.html")
```
