---
title: "`r paste0('PULCEO Data Analytics:  ', params$subfolder)`" 
params:
  rootfolder: "."
  subfolder: "sample"
knit: (function(input_file, encoding) {
  metadata <- rmarkdown::yaml_front_matter(input_file);
  out_dir <- with(metadata, paste0("reports/", params$subfolder));
  rmarkdown::render(input_file,
  encoding=encoding,
  output_file=file.path(dirname(input_file), out_dir, "index.html"))})
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---
```{r warning=FALSE, echo=FALSE}
# install_and_load <- function(pkg, mirror = "https://cloud.r-project.org") {
#   # Set default CRAN mirror and silent options
#   options(repos = c(CRAN = mirror))
#   options(install.packages.check.source = "no")
#   options(ask = FALSE)

#   # Install if missing
#   if (!requireNamespace(pkg, quietly = TRUE)) {
#     message(sprintf("Installing '%s'...", pkg))
#     install.packages(pkg, dependencies = TRUE, quiet = TRUE)
#   }

#   # Load package quietly
#   suppressPackageStartupMessages(
#     library(pkg, character.only = TRUE, quietly = TRUE, warn.conflicts = FALSE)
#   )
# }
# install_and_load("tidyverse")
# install_and_load("stringi")
# install_and_load("rjson")
# install_and_load("kableExtra")
# install_and_load("gridExtra")
#install_and_load("ggpubr")
# install_and_load("data.table")
# install_and_load("jsonlite")
install_and_load("here")

# TODO: globally load library(here)
```

```{r, include=FALSE}
# set this option in the first code chunk in the document
# TODO: maybe remove
knitr::opts_knit$set(root.dir = here())
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, include = FALSE)
```

```{r include=TRUE, echo=FALSE}
# TODO: remove
ROOTFOLDER <- "/tmp/psm-data"
```

```{r directories, include=FALSE, echo=FALSE}
source(here("includes/R/directories.R"))
source(here("includes/R/tables.R"))
```

```{r child = 'includes/topology.Rmd'}
```

```{r child = 'includes/resources.Rmd'}
```

```{r child = 'includes/events.Rmd'}
```

```{r child = 'includes/metrics.Rmd'}
```

## CPU utilization

```{r}
# CPU_UTIL <- TransfromNodeMetricsMetadata(CPU_UTIL_RAW)
```

### Nodes

```{r include=TRUE, echo=FALSE}
# CPU_UTIL_nodes_summary <- CreateSummary(filterResourceUtilForNode(CPU_UTIL, "usageCPUPercentage", "NODE", "pna-k8s-node"), "Node")
# CreateScrollableTable(CPU_UTIL_nodes_summary)
# SaveLatexTable(CPU_UTIL_nodes_summary, "CPU utilization of all nodes in \\%", "cpu-utilization-of-nodes", "cpu_util_nodes_summary.tex")
```

```{r include=TRUE, echo=FALSE}
# cpu plot
# (cpu_util_bar_plot <- GenerateBarPlotPercentage(CPU_UTIL_nodes_summary, "CPU Utilization", 1.3, 0.5))
# SavePlot("cpu_util_bar_plot.pdf", cpu_util_bar_plot)
```

```{r}
# boxplot
# cpu_box_plot <- ggplot(filterResourceUtilForNode(CPU_UTIL, "usageCPUPercentage", "NODE", "pna-k8s-node"), aes(x = sourceHost, y = X_value, group = sourceHost)) +
#   geom_boxplot()
```

```{r}
# cpu_plot_node <- ggplot(filterResourceUtilForNode(CPU_UTIL, "usageCPUPercentage", "NODE", "pna-k8s-node"), aes(x = timestamp, y = X_value, group = sourceHost)) +
#   geom_line() +
#   facet_grid(vars(sourceHost))
```

### Applications

```{r}
# CPU_UTIL_PODS <- filterResourceUtilForNode(CPU_UTIL, "usageCPUPercentage", "POD", "traefik|pulceo-node-agent|edge-iot-simulator")

# CPU_UTIL_PODS_PROCESSED <- CPU_UTIL_PODS %>%
#   group_by(nodeName) %>%
#   arrange(timestamp, .by_group = TRUE) %>%
#   mutate(id = row_number()) %>%
#   mutate(application = if_else(grepl("traefik", resourceName), "traefik",
#     if_else(grepl("pulceo-node-agent", resourceName), "pulceo-node-agent",
#       if_else(grepl("edge-iot-simulator", resourceName), "edge-iot-simulator", "")
#     )
#   ))

# (cpu_util_pods_plot <- ggplot(CPU_UTIL_PODS_PROCESSED, aes(x = id, y = X_value, colour = application)) +
#   geom_line() +
#   # ggtitle("CPU utilization of applications") +
#   ylab("Utilization (%)") +
#   xlab("Time") +
#   labs(color = "Applications") +
#   facet_grid(vars(nodeName)) +
#   theme_classic() +
#   theme(legend.position = "bottom"))

# SavePlot("cpu_util_plot_pods.pdf", cpu_util_pods_plot, 8, 6)
```

```{r include=TRUE, echo=FALSE}
# CPU_UTIL_pods_summary <- CreateSummary(filterResourceUtilForNode(CPU_UTIL, "usageCPUPercentage", "POD", "edge-iot-simulator"), "Pod")

# CPU_UTIL_PODS_SUMMARY_BY_APP <- CPU_UTIL %>%
#   filter(k8sResourceType == "POD", X_field == "usageCPUPercentage") %>%
#   group_by(nodeName, resourceName) %>%
#   summarize(
#     min = round(min(X_value), 3),
#     avg = round(mean(X_value), 3),
#     max = round(max(X_value), 3),
#     median = round(median(X_value), 3),
#     sd = round(sd(X_value), 3), .groups = "drop"
#   )
# CreateScrollableTable(CPU_UTIL_PODS_SUMMARY_BY_APP)
```

```{r}
# cpu_plot_pod_edg_iot_simulator <- ggplot(filterResourceUtilForNode(CPU_UTIL, "usageCPUPercentage", "POD", "edge-iot-simulator"), aes(x = timestamp, y = X_value, group = resourceName)) +
#   geom_line() +
#   facet_grid(vars(resourceName))
# cpu_plot_pod_pulceo_node_agent <- ggplot(filterResourceUtilForNode(CPU_UTIL, "usageCPUPercentage", "POD", "pulceo-node-agent"), aes(x = timestamp, y = X_value, group = resourceName)) +
#   geom_line() +
#   facet_grid(vars(resourceName))
# cpu_plot_pod_traefik <- ggplot(filterResourceUtilForNode(CPU_UTIL, "usageCPUPercentage", "POD", "traefik"), aes(x = timestamp, y = X_value, group = resourceName)) +
#   geom_line() +
#   facet_grid(vars(resourceName))
```

## Memory Utilization

```{r}
# MEM_UTIL <- TransfromNodeMetricsMetadata(MEM_UTIL_RAW)
```

### Nodes

```{r}
# CreateSummary(filterResourceUtilForNode(MEM_UTIL, "usageMemoryPercentage", "NODE", "pna-k8s-node"), "Node")
```

```{r include=TRUE, echo=FALSE}
# MEM_UTIL_nodes_summary <- CreateSummary(filterResourceUtilForNode(MEM_UTIL, "usageMemoryPercentage", "NODE", "pna-k8s-node"), "Node")
# CreateScrollableTable(MEM_UTIL_nodes_summary)
# SaveLatexTable(MEM_UTIL_nodes_summary, "Idle Memory utilization of all nodes in \\%", "memory-utilization-of-nodes", "mem_util_nodes_summary.tex")
```

```{r include=TRUE, echo=FALSE}
# (mem_util_bar_plot <- GenerateBarPlotPercentage(MEM_UTIL_nodes_summary, "Memory Utilization", 1.4, -1.0))
# SavePlot("mem_util_bar_plot.pdf", mem_util_bar_plot, 4, 3)
```

```{r}
# mem_box_plot <- ggplot(filterResourceUtilForNode(MEM_UTIL, "usageMemoryPercentage", "NODE", "pna-k8s-node"), aes(x = sourceHost, y = X_value, group = sourceHost)) +
#   geom_boxplot()
```

```{r}
# mem_plot_node <- ggplot(filterResourceUtilForNode(MEM_UTIL, "usageMemoryPercentage", "NODE", "pna-k8s-node"), aes(x = timestamp, y = X_value, group = sourceHost)) +
#   geom_line() +
#   facet_grid(vars(sourceHost))
# mem_plot_node_pulceo_node_agent <- ggplot(filterResourceUtilForNode(MEM_UTIL, "usageMemoryPercentage", "POD", "pulceo-node-agent"), aes(x = timestamp, y = X_value, group = sourceHost)) +
#   geom_line() +
#   facet_grid(vars(sourceHost))
# mem_plot_node_traefik <- ggplot(filterResourceUtilForNode(MEM_UTIL, "usageMemoryPercentage", "POD", "traefik"), aes(x = timestamp, y = X_value, group = sourceHost)) +
#   geom_line() +
#   facet_grid(vars(sourceHost))
```

### Applications

```{r}
# MEM_UTIL_PODS <- filterResourceUtilForNode(MEM_UTIL, "usageMemoryPercentage", "POD", "traefik|pulceo-node-agent|edge-iot-simulator")

# MEM_UTIL_PODS_PROCESSED <- MEM_UTIL_PODS %>%
#   group_by(nodeName) %>%
#   arrange(timestamp, .by_group = TRUE) %>%
#   mutate(id = row_number()) %>%
#   mutate(application = if_else(grepl("traefik", resourceName), "traefik",
#     if_else(grepl("pulceo-node-agent", resourceName), "pulceo-node-agent",
#       if_else(grepl("edge-iot-simulator", resourceName), "edge-iot-simulator", "")
#     )
#   ))

# mem_util_pods_plot <- ggplot(MEM_UTIL_PODS_PROCESSED, aes(x = timestamp, y = X_value, colour = application)) +
#   geom_line() +
#   ggtitle("Memory utilization of applications") +
#   ylab("Utilization (%)") +
#   xlab("Time") +
#   labs(color = "Applications") +
#   theme_classic() +
#   facet_grid(vars(nodeName)) +
#   theme(legend.position = "bottom")

# SavePlot("mem_util_plot_pods.pdf", mem_util_pods_plot, 8, 6)
```

```{r include=TRUE, echo=FALSE}
# MEM_UTIL_pods_summary <- CreateSummary(filterResourceUtilForNode(MEM_UTIL, "usageMemoryPercentage", "POD", "traefik"), "Pod")

# MEM_UTIL_PODS_SUMMARY_BY_APP <- MEM_UTIL %>%
#   filter(k8sResourceType == "POD", X_field == "usageMemoryPercentage") %>%
#   group_by(nodeName, resourceName) %>%
#   summarize(
#     min = round(min(X_value), 3),
#     avg = round(mean(X_value), 3),
#     max = round(max(X_value), 3),
#     median = round(median(X_value), 3),
#     sd = round(sd(X_value), 3),
#     .groups = "drop"
#   )
# CreateScrollableTable(MEM_UTIL_PODS_SUMMARY_BY_APP)
```

## Storage Utilization

```{r}
# STORAGE_UTIL <- TransfromNodeMetricsMetadata(STORAGE_UTIL_RAW)
```

### Nodes

```{r include=TRUE, echo=FALSE}
# STORAGE_UTIL_SUMMARY <- CreateSummary(filterResourceUtilForNode(STORAGE_UTIL, "usageStoragePercentage", "NODE", "pna-k8s-node"), "Node")
# CreateScrollableTable(STORAGE_UTIL_SUMMARY)
# SaveLatexTable(STORAGE_UTIL_SUMMARY, "Storage in Percent", "storage-utilization-of-nodes", "storage_util_nodes_summary.tex")
```

```{r}
# storage_plot_node <- ggplot(filterResourceUtilForNode(STORAGE_UTIL, "usageStoragePercentage", "NODE", "pna-k8s-node"), aes(x = timestamp, y = X_value, group = sourceHost)) +
#   geom_line() +
#   facet_grid(vars(sourceHost))
# storage_plot_pod_pulceo_node_agent <- ggplot(filterResourceUtilForNode(STORAGE_UTIL, "usageStoragePercentage", "POD", "pulceo-node-agent"), aes(x = timestamp, y = X_value, group = sourceHost)) +
#   geom_line() +
#   facet_grid(vars(sourceHost))
# storage_plot_pod_pulceo_node_agent <- ggplot(filterResourceUtilForNode(STORAGE_UTIL, "usageStoragePercentage", "POD", "traefik"), aes(x = timestamp, y = X_value, group = sourceHost)) +
#   geom_line() +
#   facet_grid(vars(sourceHost))
```

```{r include=TRUE, echo=FALSE}
# (storage_util_plot_nodes <- GenerateBarPlotPercentage(STORAGE_UTIL_SUMMARY, "Storage Utilization", ylim_factor = 1.4, vjust = -0.5))
# SavePlot("storage_util_plot_nodes.pdf", storage_util_plot_nodes, 4, 3)
```

### Applications

```{r include=TRUE, echo=FALSE}
# STORAGE_UTIL_pods_summary <- CreateSummaryForStorage(filterResourceUtilForNode(STORAGE_UTIL, "usageStoragePercentage", "POD", "pulceo-node-agent|edge-iot-simulator|traefik"), "Pod")
# CreateScrollableTable(STORAGE_UTIL_pods_summary)
```

## Network Utilization

```{r}
#NET_UTIL <- TransfromNodeMetricsMetadata(NET_UTIL_RAW)
```

```{r}
# INITIAL_TX_RX <- NET_UTIL %>%
#   group_by(nodeName, X_field, k8sResourceType, resourceName) %>%
#   slice(which.min(timestamp)) %>%
#   select(nodeName, sourceHost, k8sResourceType, resourceName, X_field, X_value) %>%
#   rename(X_value_initial = X_value)

# COMBINED_NET_UTIL <- left_join(NET_UTIL, INITIAL_TX_RX, join_by(nodeName, sourceHost, k8sResourceType, resourceName, X_field))
# COMBINED_NET_UTIL$X_value_final <- ((COMBINED_NET_UTIL$X_value - COMBINED_NET_UTIL$X_value_initial))
```

### Nodes

```{r}
# COMBINED_NET_UTIL_NODES <- rbind(filterResourceUtilForNode(COMBINED_NET_UTIL, "rxBytes", "NODE", "pna-k8s-node"), filterResourceUtilForNode(COMBINED_NET_UTIL, "txBytes", "NODE", "pna-k8s-node"))

# ggplot(COMBINED_NET_UTIL_NODES, aes(x = timestamp, y = X_value_final, group = sourceHost)) +
#   geom_line() +
#   facet_grid(vars(sourceHost), vars(X_field))
```

```{r}
# COMBINED_NET_UTIL_NODES_TABLE <- CreateSummaryForNetUtil(COMBINED_NET_UTIL_NODES) %>%
#   rowwise() %>%
#   pivot_wider(names_from = X_field, values_from = max)
# names(COMBINED_NET_UTIL_NODES_TABLE) <- c("Node", "Tx", "Rx")
# SaveLatexTable(COMBINED_NET_UTIL_NODES_TABLE, "Transmitted (Tx) and Received (Rx) Data in GB", "tx-rx-of-nodes", "net_util_nodes_summary.tex")
```

```{r include=TRUE, echo=FALSE}
# node_net_util <- CreateSummaryForNetUtil(COMBINED_NET_UTIL_NODES) %>%
#   rename(Node = nodeName) %>%
#   mutate(field = if_else(X_field == "rxBytes", "Rx", if_else(X_field == "txBytes", "Tx", ""))) %>%
#   rename(Traffic = field)

# (net_util_plot_nodes <- ggplot(node_net_util, aes(x = Node, y = max, fill = Node)) +
#   geom_bar(position = position_dodge(0.8), stat = "identity", width = 0.75, aes(color = Traffic)) +
#   geom_text(aes(label = format(round(max, 2), nsmall = 2), group = Traffic), position = position_dodge(0.8), angle = 90, vjust = 0.5, hjust = -0.2, size = 4, fill = "white") +
#   ggtitle("Traffic Received (Rx) and Transmitted (Tx)") +
#   ylab("Traffic in GB") +
#   xlab("Node") +
#   ylim(0, max(node_net_util$max) * 1.5) +
#   theme(legend.position = "right") +
#   scale_fill_manual(values = node_scale_fills) +
#   guides(fill = FALSE))

# SavePlot("net_util_plot_nodes.pdf", net_util_plot_nodes, 8, 6)
```

### Applications

```{r include=TRUE, echo=FALSE}
# COMBINED_NET_UTIL_POD <- rbind(filterResourceUtilForNode(COMBINED_NET_UTIL, "rxBytes", "POD", "traefik|pulceo-node-agent|edge-iot-simulator"), filterResourceUtilForNode(COMBINED_NET_UTIL, "txBytes", "POD", "traefik|pulceo-node-agent|edge-iot-simulator"))

# COMBINED_NET_UTIL_POD_PROCESSED <- COMBINED_NET_UTIL_POD %>%
#   mutate(application = if_else(grepl("traefik", resourceName), "traefik",
#     if_else(grepl("pulceo-node-agent", resourceName), "pulceo-node-agent",
#       if_else(grepl("edge-iot-simulator", resourceName), "edge-iot-simulator", "")
#     )
#   )) %>%
#   mutate(field = if_else(grepl("rxBytes", X_field), "Received (Rx)", if_else(grepl("txBytes", X_field), "Transmitted (Tx)", "")))

# (combined_net_util_pods_facet <- ggplot(COMBINED_NET_UTIL_POD_PROCESSED, aes(x = timestamp, y = X_value_final / 1024 / 1024 / 1024, colour = application)) +
#   geom_line() +
#   ylab("Traffic in GB") +
#   xlab("Time in h") +
#   scale_x_datetime(breaks = seq(min(COMBINED_NET_UTIL_POD_PROCESSED$timestamp) - 3600, max(COMBINED_NET_UTIL_POD_PROCESSED$timestamp) + 3600, by = "6 hours"), date_labels = "%H:00") +
#   labs(color = "Applications") +
#   theme_classic() +
#   facet_grid(vars(nodeName), vars(field)) +
#   theme(legend.position = "bottom"))
# SavePlot("combined_net_util_pods_facet.pdf", combined_net_util_pods_facet, 10, 6)
```

## Combined Measurements

### Nodes

#### CPU and Memory Utilization
```{r include=TRUE, echo=FALSE}
# (combined_cpu_mem_util_plot <- ggarrange(cpu_util_bar_plot, mem_util_bar_plot, ncol = 2))
# SavePlot("combined_cpu_mem_util_plot.pdf", combined_cpu_mem_util_plot, 8, 3)
```

#### Storage and Network Utilization

```{r include=TRUE, echo=FALSE}
# (combined_storage_net_util_plot <- ggarrange(storage_util_plot_nodes, net_util_plot_nodes, ncol = 2, widths = c(1, 1)))
# SavePlot("combined_storage_net_util_plot.pdf", combined_storage_net_util_plot, 8, 3)
```

### Applications

#### CPU and Memory Utilization

```{r include=TRUE, echo=FALSE}
# combined_cpu_mem_util_plot_pod <- ggarrange(cpu_util_pods_plot, mem_util_pods_plot, ncol = 2, common.legend=TRUE, legend="bottom")
# SavePlot("combined_cpu_mem_util_plot_pods.pdf", combined_cpu_mem_util_plot_pod, 8, 4)

# combined_df <- rbind(CPU_UTIL_PODS_PROCESSED, MEM_UTIL_PODS_PROCESSED)
# combined_df <- combined_df %>%
#   ungroup() %>%
#   mutate(field = if_else(combined_df$X_field == "usageCPUPercentage", "CPU Utilization",
#     if_else(combined_df$X_field == "usageMemoryPercentage", "Memory Utilization", "")
#   ))

# (combined_cpu_mem_util_plot_pod_df <- ggplot(combined_df, aes(x = timestamp, y = X_value, colour = application)) +
#   geom_line() +
#   facet_grid(nodeName ~ field) +
#   ylab("Utilization (%)") +
#   xlab("Time") +
#   scale_x_datetime(breaks = seq(min(COMBINED_NET_UTIL_POD_PROCESSED$timestamp) - 3600, max(COMBINED_NET_UTIL_POD_PROCESSED$timestamp) + 3600, by = "6 hours"), date_labels = "%H:00") +
#   labs(color = "Applications") +
#   theme_classic() +
#   theme(legend.position = "bottom"))
# SavePlot("combined_cpu_mem_util_plot_pods_facet.pdf", combined_cpu_mem_util_plot_pod_df, 10, 6)
```

## Link Quality Metrics

### ICMP RTT

```{r}
# functions
# TransfromNetworkMetricsMetadata <- function(df) {
#   df$X_field <- as.factor(df$X_field)
#   df$X_measurement <- as.factor(df$X_measurement)
#   df$metricType <- as.factor(df$metricType)
#   df$sourceHost <- as.factor(df$sourceHost)
#   df$destinationHost <- as.factor(df$destinationHost)
#   df$endTime <- as.POSIXct(df$endTime, format = "%Y-%m-%dT%H:%M:%OSZ")
#   df$jobUUID <- as.factor(df$jobUUID)
#   df <- merge(df, node_mapping, by.x = "sourceHost", by.y = "sourceHost")
#   df <- merge(df, node_mapping_dest, by.x = "destinationHost", by.y = "destinationHost")
#   return(df)
# }
```

```{r}
# ICMP_RTT <- TransfromNetworkMetricsMetadata(ICMP_RTT_RAW)

# filterICMPRTT <- function(df, field) {
#   return(df %>% filter(X_field == field))
# }
```

```{r include=TRUE, echo=FALSE}
# ICMP_RTT_SUMMARY <- filterICMPRTT(ICMP_RTT, "rttAvg")

# ICMP_RTT_SUMMARY <- ICMP_RTT_SUMMARY %>%
#   group_by(nodeName, nodeNameDest) %>%
#   summarise(
#     min = round(min(X_value), 3),
#     avg = round(mean(X_value), 3),
#     max = round(max(X_value), 3),
#     median = round(median(X_value), 3),
#     sd = round(sd(X_value), 3), .groups = "drop"
#   ) %>%
#   mutate_if(is.numeric, scale, na.rm = TRUE)
# names(ICMP_RTT_SUMMARY) <- c("$v_1$", "$v_2$", "Min", "Mean", "Max", "Med", "SD")
# CreateScrollableTable(ICMP_RTT_SUMMARY)
# ICMP_RTT_SUMMARY_TABLE <- ICMP_RTT_SUMMARY %>%
#  rowwise %>%
#  pivot_wider(names_from = nodeNameDest, values_from = rtt, names_sort = TRUE)
```
```{r}
# icmp_rtt_plot <- ggplot(ICMP_RTT_SUMMARY, aes(nodeName, nodeNameDest, fill= rtt)) +
#   geom_tile() +
#   xlab("Source Node") +
#   ylab("Destinatio Node")
```

```{r}
# SaveLatexTable(ICMP_RTT_SUMMARY, "ICMP round-trip time (ms) between nodes.", "rtt-of-nodes", "rtt_nodes_summary.tex")

# icmp_rtt_plot <- ggplot(filterICMPRTT(ICMP_RTT, "rttAvg"), aes(x = endTime, y = X_value, group = nodeName)) +
#   geom_line() +
#   facet_grid(vars(nodeName), vars(nodeNameDest))
```

```{r child = 'includes/metrics/bw.Rmd'}
```

```{r child = 'includes/metrics/combined-link-quality.Rmd'}
```

```{r child = 'includes/metrics/requests.Rmd'}
```