### UDP

```{r metrics-bw-udp-summary, include=TRUE, echo=FALSE}
UDP_BW <- filterBW(UDP_BW, c("bitrate", "jitter", "lostDatagrams", "totalDatagrams"), "RECEIVER")

UDP_BW_PACKAGE_LOSS_SUMMARY <- UDP_BW %>%
  select(endTime, nodeName, nodeNameDest, metricUUID, X_field, X_value) %>%
  filter(X_field %in% c("lostDatagrams", "totalDatagrams")) %>%
  pivot_wider(names_from = X_field, values_from = X_value) %>%
  mutate(lostDatagramsPercentage = (lostDatagrams / totalDatagrams) * 100) %>%
  group_by(nodeName, nodeNameDest) %>%
  summarise(
    min = round(min(lostDatagramsPercentage), 3),
    avg = round(mean(lostDatagramsPercentage), 3),
    max = round(max(lostDatagramsPercentage), 3),
    median = round(median(lostDatagramsPercentage), 3),
    std = round(sd(lostDatagramsPercentage), 3), .groups = "drop"
  )

UDP_BW_SUMMARY <- UDP_BW %>%
  select(endTime, nodeName, nodeNameDest, metricUUID, X_field, X_value) %>%
  filter(X_field %in% c("bitrate")) %>%
  group_by(nodeName, nodeNameDest, X_field) %>%
  summarise(
    min = round(min(X_value), 3),
    avg = round(mean(X_value), 3),
    max = round(max(X_value), 3),
    median = round(median(X_value), 3),
    std = round(sd(X_value), 3), .groups = "drop"
  ) %>%
  select(c(-X_field)) %>%
  mutate(across(where(is.numeric), round, 3))

names(UDP_BW_SUMMARY) <- c("Source", "Destination", "Min", "Mean", "Max", "Med", "SD")
CreateScrollableTable(UDP_BW_SUMMARY)
SaveLatexTable(UDP_BW_SUMMARY, "UDP bandwidth (Mbps) between nodes.", "udp-bw-between-nodes", "udp_bw_nodes_summary.tex")
```

#### Jitter

```{r metrics-bw-udp-jitter-summary, include=TRUE, echo=FALSE}
UDP_BW_SUMMARY_JITTER <- UDP_BW %>%
  select(endTime, nodeName, nodeNameDest, metricUUID, X_field, X_value) %>%
  filter(X_field %in% c("jitter")) %>%
  group_by(nodeName, nodeNameDest, X_field) %>%
  summarise(
    min = round(min(X_value), 3),
    mean = round(mean(X_value), 3),
    max = round(max(X_value), 3),
    median = round(median(X_value), 3),
    std = round(sd(X_value), 3), .groups = "drop"
  ) %>%
  select(c(-X_field)) %>%
  rename(Source = nodeName, Destination = nodeNameDest)

CreateScrollableTable(UDP_BW_SUMMARY_JITTER)

names(UDP_BW_SUMMARY_JITTER) <- c("$v_1$", "$v_2$", "Min", "Mean", "Max", "Med", "SD")
SaveLatexTable(UDP_BW_SUMMARY_JITTER, "Jitter (UDP) between nodes in ms.", "jitter-udp-bw-between-nodes", "jitter-udp_bw_nodes_summary.tex")
```

#### Package Loss

```{r metrics-bw-udp-package-loss-summary, include=TRUE, echo=FALSE}
UDP_BW_PACKAGE_LOSS <- UDP_BW %>%
  select(endTime, nodeName, nodeNameDest, metricUUID, X_field, X_value) %>%
  filter(X_field %in% c("lostDatagrams", "totalDatagrams")) %>%
  pivot_wider(names_from = X_field, values_from = X_value) %>%
  mutate(lostDatagramsPercentage = (lostDatagrams / totalDatagrams) * 100) %>%
  group_by(nodeName, nodeNameDest) %>%
  summarise(
    min = round(min(lostDatagramsPercentage), 3),
    mean = round(mean(lostDatagramsPercentage), 3),
    max = round(max(lostDatagramsPercentage), 3),
    median = round(median(lostDatagramsPercentage), 3),
    std = round(sd(lostDatagramsPercentage), 3), .groups = "drop"
  ) %>%
  rename(Source = nodeName, Destination = nodeNameDest)

CreateScrollableTable(UDP_BW_PACKAGE_LOSS)

names(UDP_BW_PACKAGE_LOSS) <- c("$v_1$", "$v_2$", "Min", "Mean", "Max", "Med", "SD")
SaveLatexTable(UDP_BW_PACKAGE_LOSS, "Package Loss (UDP) between nodes in %.", "package-loss-udp-bw-between-nodes", "package_loss_udp_bw_nodes_summary.tex")
```

```{r metrics-bw-udp-plot}
udp_bw_plot <- ggplot(filterBW(UDP_BW, "bitrate", "SENDER"), aes(x = endTime, y = X_value, group = sourceHost)) +
  geom_line() +
  facet_grid(vars(sourceHost), vars(destinationHost))
```
