---
params:
  rootfolder: "."
  subfolder: "sample"
---

```{r setup-metrics-combined-utilization, include=FALSE}
knitr::opts_knit$set(root.dir = here())
```

```{r metrics-combined-utilization-directories, child = 'directories.Rmd' }
```

```{r metrics-combined-utilization-r, include=FALSE, echo=FALSE}
source(here("includes/R/tables.R"))
```

```{r metrics-combined-utilization-sources, include=FALSE, echo=FALSE}
source(here("includes/R/nodes.R"))
source(here("includes/R/applications.R"))
source(here("includes/R/latex.R"))
source(here("includes/R/statistics.R"))
source(here("includes/R/plots.R"))
```

```{r metrics-combined-utilization-load-data-set, include=FALSE, echo=FALSE}
source(here("includes/resources/metrics/cpu-util.R"))
source(here("includes/resources/metrics/mem-util.R"))
source(here("includes/resources/metrics/storage-util.R"))
source(here("includes/resources/metrics/net-util.R"))
```

## Combined Measurements

```{r metrics-combined-utilization-nodes, eval=(HasNodes(CPU_UTIL) && HasNodes(MEM_UTIL)) || (HasNodes(STORAGE_UTIL) && HasNodes(NET_UTIL)), child = 'includes/metrics/combined-util-nodes.Rmd', include=TRUE, echo=FALSE}
```

```{r metrics-combined-utilization-applications, eval=(HasApplications(CPU_UTIL) && HasApplications(MEM_UTIL)) || (HasApplications(STORAGE_UTIL) && HasApplications(NET_UTIL)), child = 'includes/metrics/combined-util-applications.Rmd', include=TRUE, echo=FALSE}
```
