### Nodes

#### CPU and Memory Utilization

```{r metrics-combined-utilization-nodes-include-cpu-util-nodes, eval=HasNodes(CPU_UTIL), child = 'includes/metrics/cpu-util-nodes.Rmd', include=FALSE, echo=FALSE}
```

```{r metrics-combined-utilization-nodes-include-mem-util-nodes, eval=HasNodes(MEM_UTIL), child = 'includes/metrics/mem-util-nodes.Rmd', include=FALSE, echo=FALSE}
```

```{r metrics-combined-utilization-nodes-cpu-mem-util-plot, include=TRUE, echo=FALSE}
# TODO: condition
(combined_cpu_mem_util_plot <- ggarrange(cpu_util_bar_plot, mem_util_bar_plot, ncol = 2))
SavePlot("combined_cpu_mem_util_plot.pdf", combined_cpu_mem_util_plot, 8, 3)
```

#### Storage and Network Utilization

```{r metrics-combined-utilization-nodes-include-storage-util-nodes, eval=HasNodes(STORAGE_UTIL), child = 'includes/metrics/storage-util-nodes.Rmd', include=FALSE, echo=FALSE}
```

```{r metrics-combined-utilization-nodes-include-net-util-nodes, eval=HasNodes(NET_UTIL), child = 'includes/metrics/net-util-nodes.Rmd', include=FALSE, echo=FALSE}
```

```{r include=TRUE, echo=FALSE}
# TODO: condition
(combined_storage_net_util_plot <- ggarrange(storage_util_plot_nodes, net_util_plot_nodes, ncol = 2, widths = c(1, 1)))
SavePlot("combined_storage_net_util_plot.pdf", combined_storage_net_util_plot, 8, 3)
```
