---
params:
  rootfolder: "."
---

```{r setup-metrics-combined-link-quality, include=FALSE}
knitr::opts_knit$set(root.dir = here())
```

```{r metrics-combined-link-quality-directories, include=FALSE, echo=FALSE}
source(here("includes/R/directories.R"))
source(here("includes/R/tables.R"))
```

```{r metrics-combined-link-quality-sources, include=FALSE, echo=FALSE}
source(here("includes/R/links.R"))
source(here("includes/R/latex.R"))
source(here("includes/R/statistics.R"))
source(here("includes/R/plots.R"))
```

```{r metrics-combined-link-quality-load-data-set, include=FALSE, echo=FALSE}
source(here("includes/resources/metrics/rtt.R"))
source(here("includes/resources/metrics/bw.R"))
```

### Combined Link Quality Metrics

#### TCP and UDP Bandwidth

```{r metrics-combined-link-quality-metrics-tcp-udp, eval=(nrow(TCP_BW_SUMMARY) > 0 && nrow(UDP_BW_SUMMARY) > 0), include=TRUE, echo=FALSE}
COMBINED_TCP_UDP_SUMMARY <- full_join(TCP_BW_SUMMARY, UDP_BW_SUMMARY, by = c("Source", "Destination")) %>% mutate_if(is.numeric, scale, na.rm = TRUE)
names(COMBINED_TCP_UDP_SUMMARY) <- c("Source", "Destination", "Min (TCP)", "Mean (TCP)", "Max (TCP)", "Med (TCP)", "SD (TCP)", "Min (UDP)", "Mean (UDP)", "Max (UDP)", "Med (UDP)", "SD (UDP)")
CreateScrollableTable(COMBINED_TCP_UDP_SUMMARY)
SaveMultiColLatexTable(COMBINED_TCP_UDP_SUMMARY, "TCP and UDP bandwidth (ms) between nodes.", "tcp-udp-bandwidth-measured-on-links", "tcp_udp_bw_nodes_summary.tex", c("$v_1$", "$v_2$", names(TCP_BW_SUMMARY)[3:length(TCP_BW_SUMMARY)], names(UDP_BW_SUMMARY)[3:length(UDP_BW_SUMMARY)]), c(" ", " ", "TCP" = 5, "UDP" = 5))
```

#### Jitter and Package Loss

```{r metrics-combined-link-quality-metrics-jitter-package-loss, eval=(nrow(UDP_BW_SUMMARY_JITTER) > 0 && nrow(UDP_BW_PACKAGE_LOSS) > 0), include=TRUE, echo=FALSE}
COMBINED_UDP_JITTER_PACKAGE_LOSS <- full_join(UDP_BW_SUMMARY_JITTER, UDP_BW_PACKAGE_LOSS, by = c(names(UDP_BW_SUMMARY_JITTER[1]), names(UDP_BW_SUMMARY_JITTER[2])))
names(COMBINED_UDP_JITTER_PACKAGE_LOSS) <- c("Source", "Destination", "Min (Jitter)", "Mean (Jitter)", "Max (Jitter)", "Med (Jitter)", "SD (Jitter)", "Min (Package loss)", "Mean (Package loss)", "Max (Package loss)", "Med (Package loss)", "SD (Package loss)")

CreateScrollableTable(COMBINED_UDP_JITTER_PACKAGE_LOSS)
SaveMultiColLatexTable(COMBINED_UDP_JITTER_PACKAGE_LOSS, "Jitter (ms) and package loss (\\%) for UDP between nodes.", "jitter-package-loss-udp-between-nodes", "jitter-package-loss-udp-between-nodes.tex", c("$v_1$", "$v_2$", names(TCP_BW_SUMMARY)[3:length(TCP_BW_SUMMARY)], names(UDP_BW_SUMMARY)[3:length(UDP_BW_SUMMARY)]), c(" ", " ", "Jitter (ms)" = 5, "Package loss (%)" = 5), "t")
```

### Combined ICMP, TCP and UDP Bandwidth

```{r icmp-rtt-summary, eval=nrow(ICMP_RTT) > 0}
```

```{r metrics-combined-link-quality-icmp-tcp-udp-summary, eval=(nrow(ICMP_RTT_SUMMARY) > 0 && nrow(TCP_BW_SUMMARY) > 0 && nrow(UDP_BW_SUMMARY) > 0), include=TRUE, echo=FALSE}
names(ICMP_RTT_SUMMARY) <- c("Source", "Destination", "Min", "Mean", "Max", "Med", "SD")
COMBINED_ICMP_TCP_UDP_SUMMARY <- full_join(ICMP_RTT_SUMMARY, TCP_BW_SUMMARY, by = c("Source", "Destination")) %>%
  full_join(., UDP_BW_SUMMARY, by = c("Source", "Destination")) %>%
  mutate_if(is.numeric, scale, na.rm = TRUE)
names(COMBINED_ICMP_TCP_UDP_SUMMARY) <- c(
  "Source", "Destination",
  paste(c("Min", "Mean", "Max", "Med", "SD"), "(ICMP)"),
  paste(c("Min", "Mean", "Max", "Med", "SD"), "(TCP)"),
  paste(c("Min", "Mean", "Max", "Med", "SD"), "(UDP)")
)
CreateScrollableTable(COMBINED_ICMP_TCP_UDP_SUMMARY)
SaveMultiColLatexTable(COMBINED_ICMP_TCP_UDP_SUMMARY, "ICMP round-trip time (ms), TCP and UDP bandwidth (Mbps) between nodes.", "combined-icmp-tcp-udp-link-quality", "combined-icmp-tcp-udp-link-quality.tex", c("$v_1$", "$v_2$", rep(c("Min", "Mean", "Max", "Med", "SD"), 3)), c(" ", " ", "ICMP round-trip time (ms)" = 5, "TCP bandwidth (Mbps)" = 5, "UDP bandwidth (Mbps)" = 5), "t")
```
