### Applications

#### CPU and Memory Utilization

```{r metrics-cpu-utilization-applications-processed, eval=HasApplications(CPU_UTIL)}
```

```{r metrics-mem-utilization-applications-processed, eval=HasApplications(MEM_UTIL)}
```

<!-- TODO: Storage Util -->

```{r metrics-net-utilization-applications-processed, eval=HasApplications(NET_UTIL)}
```

```{r include=TRUE, echo=FALSE}
# TODO: condition
# combined_cpu_mem_util_plot_pod <- ggarrange(cpu_util_pods_plot, mem_util_pods_plot, ncol = 2, common.legend=TRUE, legend="bottom")
# SavePlot("combined_cpu_mem_util_plot_pods.pdf", combined_cpu_mem_util_plot_pod, 8, 4)

combined_df <- rbind(CPU_UTIL_PODS_PROCESSED, MEM_UTIL_PODS_PROCESSED)
combined_df <- combined_df %>%
  ungroup() %>%
  mutate(field = if_else(combined_df$X_field == "usageCPUPercentage", "CPU Utilization",
    if_else(combined_df$X_field == "usageMemoryPercentage", "Memory Utilization", "")
  ))

(combined_cpu_mem_util_plot_pod_df <- ggplot(combined_df, aes(x = timestamp, y = X_value, colour = application)) +
  geom_line() +
  facet_grid(nodeName ~ field) +
  ylab("Utilization (%)") +
  xlab("Time") +
  scale_x_datetime(breaks = seq(min(COMBINED_NET_UTIL_POD_PROCESSED$timestamp) - 3600, max(COMBINED_NET_UTIL_POD_PROCESSED$timestamp) + 3600, by = "6 hours"), date_labels = "%H:00") +
  labs(color = "Applications") +
  theme_classic() +
  theme(legend.position = "bottom"))
SavePlot("combined_cpu_mem_util_plot_pods_facet.pdf", combined_cpu_mem_util_plot_pod_df, 10, 6)
```
