### Applications

```{r metrics-cpu-utilization-applications-summary}
CPU_UTIL_pods_summary <- CreateSummary(filterResourceUtilForNode(CPU_UTIL, "usageCPUPercentage", "POD", "edge-iot-simulator"), "Pod")

CPU_UTIL_PODS_SUMMARY_BY_APP <- CPU_UTIL %>%
  filter(k8sResourceType == "POD", X_field == "usageCPUPercentage") %>%
  group_by(nodeName, resourceName) %>%
  summarize(
    min = round(min(X_value), 3),
    avg = round(mean(X_value), 3),
    max = round(max(X_value), 3),
    median = round(median(X_value), 3),
    sd = round(sd(X_value), 3), .groups = "drop"
  )
CreateScrollableTable(CPU_UTIL_PODS_SUMMARY_BY_APP)
```

```{r metrics-cpu-utilization-applications-line-plot, include=TRUE, echo=FALSE}
CPU_UTIL_PODS <- filterResourceUtilForNode(CPU_UTIL, "usageCPUPercentage", "POD", "traefik|pulceo-node-agent|edge-iot-simulator")

CPU_UTIL_PODS_PROCESSED <- CPU_UTIL_PODS %>%
  group_by(nodeName) %>%
  arrange(timestamp, .by_group = TRUE) %>%
  mutate(id = row_number()) %>%
  mutate(application = if_else(grepl("traefik", resourceName), "traefik",
    if_else(grepl("pulceo-node-agent", resourceName), "pulceo-node-agent",
      if_else(grepl("edge-iot-simulator", resourceName), "edge-iot-simulator", "")
    )
  ))

(cpu_util_pods_plot <- ggplot(CPU_UTIL_PODS_PROCESSED, aes(x = id, y = X_value, colour = application)) +
  geom_line() +
  # ggtitle("CPU utilization of applications") +
  ylab("Utilization (%)") +
  xlab("Time") +
  labs(color = "Applications") +
  facet_grid(vars(nodeName)) +
  theme_classic() +
  theme(legend.position = "bottom"))

SavePlot("cpu_util_plot_pods.pdf", cpu_util_pods_plot, 8, 6)
```

```{r metrics-cpu-utilization-applications-line-plots}
cpu_plot_pod_edg_iot_simulator <- ggplot(filterResourceUtilForNode(CPU_UTIL, "usageCPUPercentage", "POD", "edge-iot-simulator"), aes(x = timestamp, y = X_value, group = resourceName)) +
  geom_line() +
  facet_grid(vars(resourceName))
cpu_plot_pod_pulceo_node_agent <- ggplot(filterResourceUtilForNode(CPU_UTIL, "usageCPUPercentage", "POD", "pulceo-node-agent"), aes(x = timestamp, y = X_value, group = resourceName)) +
  geom_line() +
  facet_grid(vars(resourceName))
cpu_plot_pod_traefik <- ggplot(filterResourceUtilForNode(CPU_UTIL, "usageCPUPercentage", "POD", "traefik"), aes(x = timestamp, y = X_value, group = resourceName)) +
  geom_line() +
  facet_grid(vars(resourceName))
```
