```{r setup-metrics-net-utilization, include=FALSE}
knitr::opts_knit$set(root.dir = here())
```

```{r metrics-net-utilization-directories, include=FALSE, echo=FALSE}
source(here("includes/R/directories.R"))
source(here("includes/R/tables.R"))
```

```{r metrics-net-utilization-sources, include=FALSE, echo=FALSE}
source(here("includes/R/nodes.R"))
source(here("includes/R/applications.R"))
source(here("includes/R/latex.R"))
source(here("includes/R/statistics.R"))
source(here("includes/R/plots.R"))
```

```{r metrics-net-utilization-load-data-set, include=FALSE, echo=FALSE}
source(here("includes/resources/metrics/net-util.R"))
```

## Network Utilization

```{r metrics-net-utilization-combined-net-util, eval=(HasNodes(NET_UTIL) | HasApplications(NET_UTIL)) > 0}
INITIAL_TX_RX <- NET_UTIL %>%
  group_by(nodeName, X_field, k8sResourceType, resourceName) %>%
  slice(which.min(timestamp)) %>%
  select(nodeName, sourceHost, k8sResourceType, resourceName, X_field, X_value) %>%
  rename(X_value_initial = X_value)

COMBINED_NET_UTIL <- left_join(NET_UTIL, INITIAL_TX_RX, join_by(nodeName, sourceHost, k8sResourceType, resourceName, X_field))
COMBINED_NET_UTIL$X_value_final <- ((COMBINED_NET_UTIL$X_value - COMBINED_NET_UTIL$X_value_initial))
```

```{r metrics-net-utilization-nodes, eval=HasNodes(NET_UTIL) > 0, child = 'includes/metrics/net-util-nodes.Rmd', include=TRUE, echo=FALSE}
```

```{r metrics-net-utilization-applications, eval=HasApplications(NET_UTIL) > 0, child = 'includes/metrics/net-util-applications.Rmd', include=TRUE, echo=FALSE}
```
