### ICMP

```{r include=TRUE, echo=FALSE}
ICMP_RTT_SUMMARY <- filterICMPRTT(ICMP_RTT, "rttAvg")

ICMP_RTT_SUMMARY <- ICMP_RTT_SUMMARY %>%
  group_by(nodeName, nodeNameDest) %>%
  summarise(
    min = round(min(X_value), 3),
    avg = round(mean(X_value), 3),
    max = round(max(X_value), 3),
    median = round(median(X_value), 3),
    sd = round(sd(X_value), 3), .groups = "drop"
  ) %>%
  mutate_if(is.numeric, scale, na.rm = TRUE)
names(ICMP_RTT_SUMMARY) <- c("$v_1$", "$v_2$", "Min", "Mean", "Max", "Med", "SD")
CreateScrollableTable(ICMP_RTT_SUMMARY)
# ICMP_RTT_SUMMARY_TABLE <- ICMP_RTT_SUMMARY %>%
#  rowwise %>%
#  pivot_wider(names_from = nodeNameDest, values_from = rtt, names_sort = TRUE)
```
```{r}
# icmp_rtt_plot <- ggplot(ICMP_RTT_SUMMARY, aes(nodeName, nodeNameDest, fill= rtt)) +
#   geom_tile() +
#   xlab("Source Node") +
#   ylab("Destinatio Node")
```

```{r}
SaveLatexTable(ICMP_RTT_SUMMARY, "ICMP round-trip time (ms) between nodes.", "rtt-of-nodes", "rtt_nodes_summary.tex")

icmp_rtt_plot <- ggplot(filterICMPRTT(ICMP_RTT, "rttAvg"), aes(x = endTime, y = X_value, group = nodeName)) +
  geom_line() +
  facet_grid(vars(nodeName), vars(nodeNameDest))
```
