---
params:
  rootfolder: "."
  subfolder: "sample"
---

```{r setup-metrics-storage-utilization, include=FALSE}
knitr::opts_knit$set(root.dir = here())
```

```{r metrics-storage-utilization-directories, include=FALSE, echo=FALSE}
source(here("includes/R/directories.R"))
source(here("includes/R/tables.R"))
```

```{r metrics-storage-utilization-sources, include=FALSE, echo=FALSE}
source(here("includes/R/nodes.R"))
source(here("includes/R/applications.R"))
source(here("includes/R/latex.R"))
source(here("includes/R/statistics.R"))
source(here("includes/R/plots.R"))
```

```{r metrics-storage-utilization-load-data-set, include=FALSE, echo=FALSE}
source(here("includes/resources/metrics/storage-util.R"))
```

## Storage Utilization

```{r metrics-storage-utilization-nodes, eval=HasNodes(STORAGE_UTIL) > 0, child = 'includes/metrics/storage-util-nodes.Rmd', include=TRUE, echo=FALSE}
```

```{r metrics-storage-utilization-applications, eval=HasApplications(STORAGE_UTIL) > 0, child = 'includes/metrics/storage-util-applications.Rmd', include=TRUE, echo=FALSE}
```
